#ifndef DEFINE_VALUES
#define DEFINE_VALUES

#define SAMPLERATE 16000
#define DURATION_OF_FRAME 0.02f
#define NUM_OF_SAMPLES ((int)((DURATION_OF_FRAME)*(SAMPLERATE)))


#endif /*DEFINE_VALUES*/
