params = struct(...
    'attack_time', 25, ...
    'release_time', 40, ...
    'threshold_gate', 0.03, ...
    'threshold_expander', 0.15, ...
    'threshold_compressor', 0.6, ...
    'threshold_limiter', 0.85, ...
    'flat_gain', 1.8, ...
    'ng_slope', 1.8, ...
    'ex_slope', 1.4, ... %Makes voice more detalized
    'cm_ratio', 0.4, ...
    'limit_level', 0.65, ...
    'hpf_cutoff', 150 ... 
);

[in, Fs] = audioread('check_DRC_&_NoiseReduction_Clear.wav');
frame_size = 1024;
hop_size = frame_size / 2;
use_rms = false; %or false для peak

out = apply_drc_fremwise_my(in, Fs, frame_size, hop_size, params, use_rms);
sound(out, Fs);
%out = highpass(out, 100, Fs);
audiowrite('output_drc.wav', out, Fs);

figure
subplot(211)
plot(in)
subplot(212)
spectrogram(signal, 256, [], [], Fs, 'yaxis');
title('Original');

figure
subplot(211)
plot(out);
subplot(212)
spectrogram(out, 256, [], [], Fs, 'yaxis');
title('DRC Processed');
